A = {
    "1a": [
        "b", "bl",
        "d", "dr", "dw",
        "f", "fl",
        "gl", "gn", "gr",
        "hn", "hr", "hw",
        "k", "kl", "kn", "kr", "kw",
        "l",
        "m",
        "n",
        "p",
        "r",
        "s", "sk", "skr", "sl", "sm", "sn", "sp", "spl", "spr", "st", "str", "sw",
        "t",
        "þ", "þr",
        "w", "wl", "wr"
    ],
    "1b": [
        "d", "st", "w",
    ],
    "2a": [
        "b", "bl", "br",
        "dr",
        "f", "fl", "fn", "fr",
        "g", "gr",
        "hl", "hn", "hr",
        "k", "kl", "kr",
        "l",
        "n",
        "r",
        "s", "sk", "sl", "sm", "sn", "spr", "st", "str",
        "t",
        "þl", "þr",
    ],
    "2b": [
        "d",
        "l",
        "s", "sk", "sl", "sm", "spr",
    ],
    "3a": [
        "b", "br",
        "d", "dr",
        "f",
        "bi+g", "gr",
        "h", "hl", "hr",
        "k", "kl", "kr", "kw",
        "l",
        "mp",
        "n",
        "r",
        "s", "skr", "sl", "sp", "spr", "st", "sw",
        "t", "tr",
        "þ", "þr", "þw",
        "w", "wr",
    ],
    "3b": [
        "b", "br",
        "d",
        "f", "fl", "fr",
        "g", "gn",
        "h", "hn", "hr", "hw",
        "k", "kw",
        "m",
        "r",
        "s", "sk", "sm", "sn", "st", "sw",
        "t",
        "þ", "þr", "þw",
        "w", "wr",
    ],
    "3c": [
        "sp",
    ],
    "4a": [
        "b", "br",
        "dw",
        "f",
        "h", "hl",
        "kl", "kw",
        "n",
        "sk", "st", "sw",
        "t", "tr",
        "þw",
        "w",
    ],
    "4b": [
        "k", "kn", "tr", "w",
    ],
    "5a": [
        "d", "dr",
        "f", "fr",
        "g",
        "hl", "hw",
        "j",
        "kn", "kw",
        "l",
        "m",
        "n",
        "pl",
        "r",
        "s", "sk", "skr", "spr", "sw",
        "tr",
        "þr",
        "w", "wr",
        "ga+w",
        "∅",
    ],
    "5b": [
        "s",
    ],
    "5J": [
        "b",
        "fr",
        "l",
        "s",
        "þ",
    ],
    "6a": [
        "∅",
        "b",
        "d", "dr",
        "f", "fl",
        "g", "gn", "gr",
        "hl", "hn",
        "k",
        "l",
        "m",
        "s", "sk", "sl", "sn", "sp", "st",
        "t",
        "þw",
        "w",
    ],
    "6b": [
        "d",
        "g",
        "kl",
    ],
    "6J": [
        "fr",
        "h", "hl",
        "kw",
        "s", "sk", "st", "sw",
        "w",
    ],
    "7a": [
        "∅",
        "fr",
        "h",
        "l",
        "m",
        "sk", "sw",
        "t",
        "þl",
    ],
    "7b": [
        "∅",
        "b", "br",
        "d",
        "h", "hl",
        "n",
        "skr", "st",
    ],
    "7c": [
        "∅",
        "b", "bl",
        "d",
        "f",
        "g",
        "h",
        "s", "sk", "sp", "st",
        "w",
    ],
    "7d": [
        "b", "bl", "br",
        "d", "dr",
        "g", "gr",
        "hw",
        "kn", "kr",
        "l",
        "m",
        "n",
        "r",
        "s", "sl", "st",
        "t",
        "þr",
        "w",
    ],
    "7e": [
        "b", "bl", "bn", "br",
        "d",
        "fl",
        "gl", "gr",
        "hl", "hr", "hw",
        "kn",
        "r",
        "sn", "sp", "sw",
        "þr",
    ],
    "7J": [
        "w",
    ],
}

B = {
    "1a": [
        "b",
        "d",
        "f",
        "g", "gw",
        "h", "hw",
        "k", "kw",
        "m",
        "n",
        "p",
        "s", "st",
        "t",
        "þ",
        "w",
        "∅",
    ],
    "1b": [
        "g", "k"
    ],
    "2a": [
        "b",
        "d",
        "f",
        "g",
        "h",
        "k",
        "p",
        "s", "st",
        "t",
        "þ",
        "w",
    ],
    "2b": [
        "g",
        "k",
        "l",
        "p",
        "t",
    ],
    "3a": [
        "mb", "mm", "mp",
        "nd", "ng", "ngw", "nh", "nhw", "nk", "nkw", "nn", "ns", "nt", "nþ",
    ],
    "3b": [
        "gd", "gn",
        "hs", "ht",
        "lb", "ld", "lg", "lh", "lk", "ll", "lp", "lt", "lw",
        "rb", "rd", "rf", "rg", "rh", "rk", "rp", "rr", "rs", "rt", "rþ", "rz",
        "sk", "skw", "sp", "st",
        "wt",
    ],
    "3c": [
        "rn",
    ],
    "4a": [
        "k",
        "l",
        "m",
        "n",
        "r",
    ],
    "4b": [
        "d",
        "l",
        "m",
    ],
    "5a": [
        "b",
        "d",
        "f",
        "g", "gn",
        "h", "hn", "hw",
        "k", "kk", "kw",
        "p",
        "s",
        "t",
        "þ",
        "w",
    ],
    "5b": [
        "f",
    ],
    "5J": [
        "d+j",
        "g+j",
        "t+j",
    ],
    "6a": [
        "b",
        "d",
        "g",
        "h", "hwn",
        "k",
        "l",
        "n", "nd",
        "p",
        "r",
        "þ",
    ],
    "6b": [
        "u+j",
    ],
    "6J": [
        "b+j",
        "f+j",
        "h+j", "hs+ij",
        "p+j",
        "r+j",
        "þ+j",
    ],
    "7a": [
        "d",
        "h",
        "k",
        "p",
        "s",
        "t",
        "þ",
    ],
    "7b": [
        "d",
        "f",
        "g",
        "k",
        "p",
        "s",
        "t",
    ],
    "7c": [
        "ld", "nd",
        "lg", "ng",
        "nh",
        "rj", "wj",
        "lk", "sk",
        "ll",
        "nn",
        "lt",
        "lþ",
        "ww",
    ],
    "7d": [
        "∅",
        "d",
        "g",
        "j",
        "k",
        "p",
        "s",
        "t",
    ],
    "7e": [
        "∅",
        "d",
        "g",
        "k",
        "n",
        "p",
        "s",
        "t",
        "w", "ww",
    ],
    "7J": [
        "p+ij",
    ],
}

MID = {
    "1a": ["ī"],
    "1b": ["i"],
    "2a": ["eu", "ew"],
    "2b": ["ū"],
    "3a": ["i"],
    "3b": ["e"],
    "3c": ["u"],
    "4a": ["e"],
    "4b": ["u"],
    "5a": ["e"],
    "5b": ["u"],
    "5J": ["i"],
    "6a": ["a"],
    "6b": ["a"],
    "6J": ["a"],
    "7a": ["ai"],
    "7b": ["au"],
    "7c": ["a"],
    "7d": ["ē"],
    "7e": ["ō"],
    "7J": ["ō"],
}

with open("strong-verb-list.txt") as f:
    line_number = 0
    for line in f:
        line_number += 1
        try:
            c, w, t, x = line.strip().split("|")
        except ValueError:
            print(line_number)
            raise

        a, b = t.split("_")
        if a == "∅":
            assert w.startswith("*"), (w, a)
            rest = w[len("*"):]
        else:
            assert w.startswith("*" + a), (w, a)
            rest = w[len("*" + a):]
        if b == "∅":
            assert rest.endswith("aną")
            mid = rest[:-len("aną")]
        else:
            assert rest[:-3].endswith(b.replace("+", "")), (rest[:-3], b.replace("+", ""))
            mid = rest[:-len(b.replace("+", "") + "aną")]

        print(c, w, a, mid, b)
        if a not in A[c]:
            print(f"@@@ {a} can start class {c}")
        if mid not in MID[c]:
            print(f"@@@ {a} can be middle vowel in class {c}")
        if b not in B[c]:
            print(f"@@@ {b} can end class {c}")
